# Generated by Django 4.0.2 on 2022-03-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=222)),
                ('credit', models.IntegerField(default=0)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
